### ISSUE TITLE
Can't get Apache to pick up mod_php settings using libapache2-mod-php7.0 instead of FPM

### ISSUE THREAD

**Issue by TechFanDan** [geerlingguy/ansible-role-php#189]
I'm currently using `ansible-role-php` but not `ansible-role-apache`. Should I be? Is this a requirement?

After a successful PHP install, Apache isn't parsing PHP files. I'm setting `fpm` to **false** and I did specify the package `libapache2-mod-php7.0`.

Current configuration:

```
roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-fpm
        - php7.0-common
        - php7.0-gd
        - php7.0-json
        - php7.0-cli
        - php7.0-curl
        - libapache2-mod-php7.0
        - php7.0-intl
        - php7.0-mbstring
        - php7.0-xml
      php_webserver_daemon: "apache2"
      php_mysql_package: php7.0-mysql
      php_enable_php_fpm: false
```

**Comment by geerlingguy** [comment]
@TechFanDan - This should work (that's how I have the role configured on a few of my older Apache servers), but have you restarted Apache (or the entire server)?

Also, are you using this with something like Drupal VM? If so, you also need to make sure you aren't using `FilesMatch` to tell Apache to use fcgi: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L102

**Comment by TechFanDan** [comment]
@geerlingguy Yes, I did restart it. This is also a very vanilla LAMP install, nothing fancy, just PHP (via `ansible-role-php`, Composer (via `ansible-role-composer`), MySQL and Apache in Ubuntu 16.04.

I did a grep for PHP and found all instances residing in mods-available or conf-available. No hits for *-enabled.

I then listed Apache2 modules and no instances of PHP loaded either. I'm assuming that the `ansible-role-php` should have loaded them by creating the appropriate symbolic links in *-enabled?

Not excluding operator error here BTW, I may have missed something obvious.

**Comment by geerlingguy** [comment]
@TechFanDan - If you're using the packages to install Apache (e.g. using `apt-get` or ansible's `apt` or `package` module, then installing `libapache2-mod-php5` (or `-php5.6` or `-php7.0` if using something like Ondrej's PPA) should do everything for you.

It looks like you have `libapache2-mod-php7.0` in that list... so it seems like it should be working. If, on the server, you run `php -v`, what's the output? Also, `php -i`?

**Comment by TechFanDan** [comment]
Here you go.

```
me@server:~$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/apcu.so' - /usr/lib/php/20151012/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
```

```
me@server:~$ php -i
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/apcu.so' - /usr/lib/php/20151012/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
phpinfo()
PHP Version => 7.0.15-0ubuntu0.16.04.4
```
It doesn't seem to be able to find apcu.so. I'm still missing the symlink in mods-enabled too.

**Comment by oxyc** [comment]
https://github.com/geerlingguy/ansible-role-php#apcu-related-variables

**Comment by TechFanDan** [comment]
@oxyc Ok, got rid of the error. I wasn't providing the right module for APC in the list.

Still no symlink in mods-enabled.

**Comment by TechFanDan** [comment]
Decided to give this another try and downloaded the source code to see if I couldn't figure anything out.

I ran `grep -r apache2` in the source code.

I didn't find any reference to `/etc/apache2` anywhere. Shouldn't there be commands that create something in that folder, such as a symlink (ie. mod-enabled)?

**Comment by fullofcaffeine** [comment]
I'm having the same problem on Ubuntu Bionic, role executes successfully after `geerlingguy.apache` but php files are not being parsed.

**Comment by fullofcaffeine** [comment]
Any news here?
